In [39]:

import pandas as pd
import runpy as np
import matplotlib.pyplot as plt


df = pd.read_excel(r"C:\Users\uilli\Downloads\arquivo_R\Banco.xlsx")
#df.head()
#df.tall()
#df.dtypes # tipos de dados
#df.rename(columns={'datnasc':'data_nascimento'})

# listas []
# Dicionarios{}
# (Função)

#plt.boxplot(df.salário) #visualiza os outlier

#df.head()

#missing = df.isnull.sum()
#missing

df.salarin.mean()
df['salarin'].fillna(df['salarin'].mean(),inplace = True)
df.head
#dropando coluna
eliminando = df.drop(['datanasc'],axis=1)  #aaxis 1 = colina , #axis = 0 Linha
eliminando.head()
#dropando linha
eliminando = df.drop([0],axis=0)  #aaxis 1 = colina , #axis = 0 Linha
eliminando.head()

#criando faixa salarial 

bins = [1,8,15,22]
grupo = ['Inicio','Itermediario','Avançado']
df['fax_estudo'] = pd.cut(df['estudo'],bins,labels = grupo)

df["fax_estudo"].value_counts()

pd.crosstab(df.sexo,df.catemp,margins=True,margins_name="Total")

C:\Users\uilli\AppData\Local\Temp\ipykernel_16528\4111127155.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salarin'].fillna(df['salarin'].mean(),inplace = True)

catemp      A   B    C  Total
sexo
Feminino   12   1  220    233
Masculino  82  26  170    278
Total      94  27  390    511